### PR TITLE
chore: Improve template

### PR DESCRIPTION
**Pull request by ben-wilson-peak**
## Description

This pull request is aiming to reduce the amount of information that appears on the rendered output. This PR should serve as a visual example of the improved rendered output

- [Jira Ticket](https://example.com/) // Won't include internal link for this public PR

## Checklist

- [x] ❓ I have performed a self-review
- [x] 📝 The commit message is clear and descriptive
- [ ] ✅ I have added tests that prove my fix is effective or that my feature works
- [ ] 📄 The documentation is up-to-date
- [x] 🔐 The security considerations section in the PR description is complete - **Please do not remove this**

## Dependencies

- N/A

**Does this PR introduce a breaking change?** 

- [ ] Yes
- [x] No

## Security Considerations

- [x] Yes
- [ ] No

The security section hasn't had anything removed, it just hides the thought prompt away to a comment which is visual to the person writing the PR

## Types of change

- [ ] 🐛 Bug fix (non-breaking change which fixes an issue)
- [ ] ✨ New feature (non-breaking change which adds functionality)
- [ ] 💥 Breaking change (fix or feature that would cause existing functionality not to work as expected)
- [x] 🛠 Adding or updating configuration files, development scripts etc.
- [x] ♻️ Refactoring (no functional changes, no API changes)
- [x] 🧹 Chore (removing redundant files, fixing typos etc.)
- [ ] 📄 Documentation Update
- [ ] ❓ Other (if none of the other choices applies)

## Additional information

N/A

### CODE REVIEW

**Comment by aidanpeak** [comment]
LGTM

**Review by aidanpeak — APPROVED** [review]

**Review by niravpeak — APPROVED** [review]
It does reduce clutter from PR.

**Review by techytushar — APPROVED** [review]

**Review by parul157 — APPROVED** [review]
looks good. Is it worth adding a field in the end saying `Steps to Test`

**Comment by ben-wilson-peak** [comment]
> looks good. Is it worth adding a field in the end saying `Steps to Test`

I think that's a required field in the jira ticket, but that's a great question, is some of the fields on here redundant and is jira the preferred source of truth for these? I'm too green in this company to really answer that one. If you'd like me to add it I'm more than happy to :)

**Comment by parul157** [comment]
> > looks good. Is it worth adding a field in the end saying `Steps to Test`
> 
> I think that's a required field in the jira ticket, but that's a great question, is some of the fields on here redundant and is jira the preferred source of truth for these? I'm too green in this company to really answer that one. If you'd like me to add it I'm more than happy to :)

yeah, Jira has it so let's not duplicate the work. 👍

**Review by azhar22k — APPROVED** [review]

**Pull request merged**
